[dotfiles]
"~/.config/mise/config.toml" = { source = "mise.toml" }
"~/.scripts" = { source = "scripts" }
"~/.bashrc.d" = { source = "profile" }
"~/.config/peanutbutter" = { source = "peanutbutter" }
"~/.config/zellij" = { source = "zellij" }



[tasks.where]
run = "pwd; echo {{ config_root }}"

[tools]
fzf = "latest"
gh = "latest"
"github:calamity-m/peanutbutter" = "latest"
lazygit = "latest"
zellij = "latest"
